services:
  dryft-api:
    image: ghcr.io/dryft-app/dryft-api:latest
    restart: always
    env_file:
      - .env.prod
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dryft-api.rule=Host(`api.dryft.ca`)"
      - "traefik.http.routers.dryft-api.entrypoints=websecure"
      - "traefik.http.routers.dryft-api.tls=true"
      - "traefik.http.routers.dryft-api.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      - traefik
      - db-dev

networks:
  traefik:
    external: true
  db-dev:
    external: true
