version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    command: 
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock