version: "3"
services:
  watchtower:
    container_name: watchtower
    env_file:
      - .env
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock