services:
  postgres:
    container_name: dev-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev_db:/var/lib/postgresql/data
    restart: always
    networks:
      - db-dev

volumes:
  postgres_data_dev_db:

networks:
  db-dev:
    external: true
