services:
  capstone-api:
    image: ghcr.io/shahbaz-athwal/capstone-backend:latest
    restart: always
    env_file:
      - .env.prod
    deploy:
      mode: replicated
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.capstone-api.rule=Host(`capstone-api.shahcodes.in`)"
      - "traefik.http.routers.capstone-api.entrypoints=websecure"
      - "traefik.http.routers.capstone-api.tls=true"
      - "traefik.http.routers.capstone-api.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      - traefik
      - db-dev

networks:
  traefik:
    external: true
  db-dev:
    external: true
