services:
  app:
    container_name: github-readme-stats
    image: ghcr.io/shahbaz-athwal/github-readme-stats:linux-amd64-mini
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.github-readme-stats.rule=Host(`github-stats.shahcodes.in`)"
      - "traefik.http.routers.github-readme-stats.entrypoints=websecure"
      - "traefik.http.routers.github-readme-stats.tls=true"
      - "traefik.http.routers.github-readme-stats.tls.certresolver=myresolver"
    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true
